/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mx.unam.fciencias.edd;

import mx.unam.fciencias.edd.laberinto.Laberinto;

public class App {

    public static void main(String[] args) {
        
    }
}
